Repository Nexters/payout-server, pull requests merged in 2024-02, with the labels that each got.

#20 fix: fix dividend batch service and refactor test
  batch/src/main/java/nexters/payout/batch/application/DividendBatchService.java
  batch/src/main/java/nexters/payout/batch/application/StockBatchService.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpFinancialClient.java
  batch/src/test/java/nexters/payout/batch/application/DividendBatchServiceTest.java
  batch/src/test/java/nexters/payout/batch/application/StockBatchServiceTest.java
  domain/src/main/java/nexters/payout/domain/dividend/repository/DividendRepository.java
  domain/src/testFixtures/java/nexters/payout/domain/DividendFixture.java
Labels: bug, refactor

#21 setting: CD 환경 구축
  .github/workflows/deploy.yml
  api-server/Dockerfile
  batch/Dockerfile
  docker-compose.yml
Labels: setting

#24 feat: implement getStock API
  .gitignore
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/SectorRatioResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/common/IntegrationTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  batch/src/main/java/nexters/payout/batch/application/DividendBatchService.java
  batch/src/main/java/nexters/payout/batch/application/FinancialClient.java
  batch/src/main/java/nexters/payout/batch/application/StockBatchService.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpDto.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpFinancialClient.java
  batch/src/test/java/nexters/payout/batch/application/DividendBatchServiceTest.java
  batch/src/test/java/nexters/payout/batch/application/LatestStockFixture.java
  batch/src/test/java/nexters/payout/batch/application/StockBatchServiceTest.java
  batch/src/test/java/nexters/payout/batch/common/AbstractBatchServiceTest.java
  build.gradle
  core/src/main/java/nexters/payout/core/time/DateFormat.java
  core/src/main/java/nexters/payout/core/time/InstantProvider.java
  domain/build.gradle
  domain/src/main/generated/nexters/payout/domain/QBaseEntity.java
  domain/src/main/generated/nexters/payout/domain/dividend/domain/QDividend.java
  domain/src/main/generated/nexters/payout/domain/stock/domain/QStock.java
  domain/src/main/java/nexters/payout/domain/BaseEntity.java
  domain/src/main/java/nexters/payout/domain/dividend/application/DividendCommandService.java
  domain/src/main/java/nexters/payout/domain/dividend/application/dto/UpdateDividendRequest.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/Dividend.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/repository/DividendRepository.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/repository/DividendRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/repository/DividendRepositoryImpl.java
  domain/src/main/java/nexters/payout/domain/stock/application/StockCommandService.java
  domain/src/main/java/nexters/payout/domain/stock/application/dto/UpdateStockRequest.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Exchange.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Sector.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Stock.java
  domain/src/main/java/nexters/payout/domain/stock/domain/repository/StockRepository.java
  domain/src/main/java/nexters/payout/domain/stock/domain/service/DividendAnalysisService.java
  domain/src/main/java/nexters/payout/domain/stock/domain/service/SectorAnalysisService.java
  domain/src/main/resources/db/migration/V2__column_update.sql
  domain/src/test/java/nexters/payout/domain/stock/service/DividendAnalysisServiceTest.java
  domain/src/test/java/nexters/payout/domain/stock/service/SectorAnalysisServiceTest.java
  domain/src/testFixtures/java/nexters/payout/domain/DividendFixture.java
  domain/src/testFixtures/java/nexters/payout/domain/StockFixture.java
Labels: enhancement

#30 setting: update prod config for ncp
  api-server/Dockerfile
  api-server/src/main/resources/application-prod.yml
  batch/Dockerfile
  batch/src/main/resources/application-prod.yml
  core/src/main/resources/logback-spring.xml
  docker-compose.yml
  domain/src/main/resources/application-prod.yml
Labels: setting

#32 feat: update swagger content
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
Labels: enhancement

#28 feat: update sector information
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/SectorRatioResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockResponse.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  batch/src/main/java/nexters/payout/batch/application/DividendBatchService.java
  batch/src/main/java/nexters/payout/batch/application/FinancialClient.java
  batch/src/main/java/nexters/payout/batch/application/StockBatchService.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpFinancialClient.java
  batch/src/main/resources/application.yml
  domain/src/main/java/nexters/payout/domain/dividend/application/DividendCommandService.java
  domain/src/main/java/nexters/payout/domain/stock/application/StockCommandService.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Sector.java
  domain/src/main/java/nexters/payout/domain/stock/domain/service/DividendAnalysisService.java
  domain/src/main/java/nexters/payout/domain/stock/domain/service/SectorAnalysisService.java
  domain/src/test/java/nexters/payout/domain/stock/service/SectorAnalysisServiceTest.java
Labels: enhancement, refactor

#34 feat: implement stockSearch API
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  batch/src/main/java/nexters/payout/batch/PayoutBatchApplication.java
  batch/src/main/java/nexters/payout/batch/application/FinancialClient.java
  batch/src/main/java/nexters/payout/batch/application/StockBatchService.java
  batch/src/main/java/nexters/payout/batch/application/StockLogo.java
  batch/src/main/java/nexters/payout/batch/infra/ninjas/NinjasDto.java
  batch/src/main/java/nexters/payout/batch/infra/ninjas/NinjasFinancialClient.java
  batch/src/main/java/nexters/payout/batch/infra/ninjas/NinjasProperties.java
  batch/src/main/resources/application-dev.yml
  batch/src/main/resources/application-prod.yml
  domain/src/main/java/nexters/payout/domain/stock/application/StockCommandService.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Sector.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Stock.java
  domain/src/main/java/nexters/payout/domain/stock/domain/repository/StockRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/stock/domain/repository/StockRepositoryImpl.java
  domain/src/testFixtures/java/nexters/payout/domain/StockFixture.java
Labels: enhancement

#36 fix: add missing value to stock response
  api-server/Dockerfile
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockResponse.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  batch/Dockerfile
Labels: bug

#40 fix: add pagination to stock search api
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  domain/src/main/java/nexters/payout/domain/stock/domain/repository/StockRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/stock/domain/repository/StockRepositoryImpl.java
Labels: bug

#38 fix: fix scheduler cycle and logging option
  batch/src/main/java/nexters/payout/batch/application/DividendBatchService.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpFinancialClient.java
  batch/src/main/resources/application-prod.yml
Labels: enhancement

#37 feat: implement monthly/yearly dividend API
  api-server/src/main/java/nexters/payout/apiserver/PayoutApiServerApplication.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/DividendQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/request/DividendRequest.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/request/TickerShare.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/MonthlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/SingleMonthlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/SingleYearlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/YearlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/presentation/DividendController.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/presentation/DividendControllerDocs.java
  api-server/src/main/resources/application-dev.yml
  api-server/src/main/resources/application-prod.yml
  api-server/src/main/resources/application-test.yml
  api-server/src/test/java/nexters/payout/apiserver/dividend/application/DividendQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/dividend/common/GivenFixtureTest.java
  api-server/src/test/java/nexters/payout/apiserver/dividend/presentation/DividendControllerTest.java
  core/src/main/java/nexters/payout/core/time/InstantProvider.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/repository/DividendRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/repository/DividendRepositoryImpl.java
  domain/src/testFixtures/java/nexters/payout/domain/DividendFixture.java
Labels: enhancement

#44 refactor: update domain package structure and deployment environments
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  batch/src/main/resources/application-dev.yml
  core/src/main/resources/logback-spring.xml
  docker-compose.yml
  domain/src/main/java/nexters/payout/domain/dividend/domain/repository/DividendRepository.java
  domain/src/main/java/nexters/payout/domain/dividend/infra/DividendRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/dividend/infra/DividendRepositoryImpl.java
  domain/src/main/java/nexters/payout/domain/stock/domain/repository/StockRepository.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryImpl.java
Labels: refactor, setting

#47 feat: implement upcoming dividend stock api
  .gitignore
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/DividendQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/presentation/DividendController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/UpcomingDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
  api-server/src/test/java/nexters/payout/apiserver/dividend/common/GivenFixtureTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  batch/src/main/java/nexters/payout/batch/application/DividendBatchService.java
  batch/src/main/java/nexters/payout/batch/application/FinancialClient.java
  batch/src/main/java/nexters/payout/batch/application/StockBatchService.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpFinancialClient.java
  batch/src/main/resources/application-dev.yml
  batch/src/main/resources/application-prod.yml
  batch/src/main/resources/application-test.yml
  batch/src/test/java/nexters/payout/batch/application/DividendBatchServiceTest.java
  core/src/main/java/nexters/payout/core/time/DateFormat.java
  core/src/main/java/nexters/payout/core/time/InstantProvider.java
  domain/src/main/generated/nexters/payout/domain/stock/domain/QStock.java
  domain/src/main/java/nexters/payout/domain/BaseEntity.java
  domain/src/main/java/nexters/payout/domain/dividend/application/DividendCommandService.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/Dividend.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/repository/DividendRepository.java
  domain/src/main/java/nexters/payout/domain/dividend/infra/DividendRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/dividend/infra/DividendRepositoryImpl.java
  domain/src/main/java/nexters/payout/domain/stock/domain/repository/dto/StockDividendDto.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryImpl.java
Labels: enhancement

#51 fix: fix cron of scheduler
  .github/workflows/deploy.yml
  batch/src/main/resources/application-dev.yml
  batch/src/main/resources/application-prod.yml
Labels: bug

#55 refactor: add required option to swagger
  .github/workflows/deploy.yml
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/request/DividendRequest.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/request/TickerShare.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/MonthlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/SingleMonthlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/SingleYearlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/YearlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/presentation/DividendControllerDocs.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/request/SectorRatioRequest.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/request/TickerShare.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/SectorRatioResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDividendYieldResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/UpcomingDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
Labels: refactor

#57 fix: fix getSectorRatio API response
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/SectorRatioResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockShareResponse.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
Labels: bug

#54 setting: apply zero-downtime deployment
  .github/workflows/deploy.yml
  api-server/src/main/java/nexters/payout/apiserver/config/WebConfig.java
  api-server/src/main/resources/application-prod.yml
  deploy.sh
  docker-compose.yml
  nginx/nginx.conf
Labels: setting

#62 chore: update swagger & blue/green deployment
  .github/workflows/deploy.yml
  .gitignore
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/DividendQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/request/DividendRequest.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/MonthlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/SingleMonthlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/SingleYearlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/YearlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/request/SectorRatioRequest.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/request/TickerShare.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/SectorRatioResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDividendYieldResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/UpcomingDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
  api-server/src/main/resources/application-prod.yml
  batch/src/main/java/nexters/payout/batch/application/StockBatchService.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpDto.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpFinancialClient.java
  batch/src/main/resources/application-prod.yml
  deploy.sh
  domain/src/main/java/nexters/payout/domain/stock/application/StockCommandService.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Sector.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Stock.java
  domain/src/main/resources/application-prod.yml
  domain/src/main/resources/db/migration/V3__add_stock_logo_column.sql
  domain/src/main/resources/db/migration/V4__add_sector.sql
  nginx/nginx.conf
Labels: enhancement, setting

#64 fix: fix get highest dividend yield api
  .github/workflows/deploy.yml
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryImpl.java
  domain/src/test/java/nexters/payout/domain/stock/service/DividendAnalysisServiceTest.java
Labels: bug

#68 setting: set up server in korean region
  .github/workflows/deploy.yml
  batch/src/main/java/nexters/payout/batch/application/DividendBatchService.java
  batch/src/main/resources/application-prod.yml
  deploy.sh
Labels: setting

#69 setting: add docker, docker-compose installation script
  .github/workflows/deploy.yml
  api-server/src/main/java/nexters/payout/apiserver/config/WebConfig.java
  deploy.sh
Labels: setting

#70 setting: add redirect logic to nginx.conf
  domain/src/main/java/nexters/payout/domain/stock/domain/Sector.java
  nginx/nginx.conf
Labels: setting

#72 refactor: refactor code & add edge case features
  .github/workflows/deploy.yml
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/DividendQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/dto/response/MonthlyDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/dividend/presentation/DividendController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/DividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDividendYieldResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockShareResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/UpcomingDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/test/java/nexters/payout/apiserver/dividend/common/GivenFixtureTest.java
  api-server/src/test/java/nexters/payout/apiserver/dividend/presentation/DividendControllerTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  batch/src/main/java/nexters/payout/batch/application/FinancialClient.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpFinancialClient.java
  batch/src/main/java/nexters/payout/batch/infra/ninjas/NinjasDto.java
  batch/src/test/java/nexters/payout/batch/application/DividendBatchServiceTest.java
  core/src/main/java/nexters/payout/core/time/DateFormat.java
  core/src/main/java/nexters/payout/core/time/InstantProvider.java
  domain/src/main/java/nexters/payout/domain/stock/domain/service/StockDividendAnalysisService.java
  domain/src/test/java/nexters/payout/domain/stock/service/StockDividendAnalysisServiceTest.java
  domain/src/testFixtures/java/nexters/payout/domain/DividendFixture.java
Labels: bug, refactor

#74 fix: add lastModifiedAt field to sector insight apis
  .github/workflows/deploy.yml
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/DividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/SingleStockDividendYieldResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/SingleUpcomingDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDividendYieldResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/UpcomingDividendResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
Labels: bug

#76 fix: add sector value to sector insight api
  .github/workflows/deploy.yml
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/SectorRatioResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  api-server/src/test/java/nexters/payout/apiserver/stock/presentation/integration/StockControllerTest.java
  batch/src/main/java/nexters/payout/batch/infra/fmp/FmpFinancialClient.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Sector.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryImpl.java
Labels: bug
