Repository Nexters/payout-server, pull requests merged in 2024-03, with the labels that each got.

#78 fix: add updated time field to stock api
  .github/workflows/deploy.yml
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/dto/response/StockDetailResponse.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockController.java
  api-server/src/main/java/nexters/payout/apiserver/stock/presentation/StockControllerDocs.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
Labels: bug

#80 docs: update README
  .github/workflows/deploy.yml
  README.md
Labels: documentation

#84 setting: transfer server to us region
  .github/workflows/deploy.yml
Labels: setting

#86 refactor: code refactoring
  README.md
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/DividendQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/main/resources/application-prod.yml
  core/src/main/java/nexters/payout/core/time/InstantProvider.java
  domain/src/main/generated/nexters/payout/domain/QBaseEntity.java
  domain/src/main/generated/nexters/payout/domain/dividend/domain/QDividend.java
  domain/src/main/java/nexters/payout/domain/BaseEntity.java
  domain/src/main/java/nexters/payout/domain/dividend/application/dto/UpdateDividendRequest.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/Dividend.java
  domain/src/main/java/nexters/payout/domain/dividend/domain/repository/DividendRepository.java
  domain/src/main/java/nexters/payout/domain/stock/application/dto/UpdateStockRequest.java
  domain/src/main/java/nexters/payout/domain/stock/domain/Stock.java
  domain/src/main/java/nexters/payout/domain/stock/domain/exception/TickerNotFoundException.java
  domain/src/main/java/nexters/payout/domain/stock/domain/service/SectorAnalysisService.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryCustom.java
  domain/src/main/java/nexters/payout/domain/stock/infra/StockRepositoryImpl.java
Labels: documentation, refactor

#87 refactor: change dependency direction
  .gitignore
  api-server/src/main/java/nexters/payout/apiserver/dividend/application/StockDividendQueryServiceImpl.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockDividendQueryService.java
  api-server/src/main/java/nexters/payout/apiserver/stock/application/StockQueryService.java
  api-server/src/test/java/nexters/payout/apiserver/stock/application/StockQueryServiceTest.java
  domain/src/main/generated/nexters/payout/domain/QBaseEntity.java
  domain/src/main/generated/nexters/payout/domain/dividend/domain/QDividend.java
  domain/src/test/java/nexters/payout/domain/stock/service/StockDividendAnalysisServiceTest.java
Labels: refactor
